version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sAsi@2932
      MYSQL_DATABASE: students_db
    ports:
      - "3308:3306"

  webapplication:
    image: web-application
    ports:
      - "8888:8888"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: sAsi@2932